# productsSample = [
#     'Bạn có sẵn iPhone mới nhất không ?', 
#     'Giá của Samsung Galaxy_S21 là bao_nhiêu ?', 
#     'OnePlus 9 Pro có màu xanh không ?', 
#     'Thông_số kỹ_thuật của Google Pixel 6 là gì ?', 
#     'Huawei P50_Pro có sẵn ở cửa_hàng của bạn không ?', 
#     'iPhone 13 có những màu gì ?', 
#     'Có giảm_giá nào cho Samsung_Galaxy_Note 20 không ?', 
#     'Sony Xperia 1 III có sẵn không ?', 
#     'Cửa_hàng của bạn có Google_Pixel mới nhất không ?', 
#     'Có chương_trình khuyến_mãi nào cho OnePlus Nord không ?', 
#     'Dung_lượng lưu_trữ của Samsung Galaxy_S21 là bao_nhiêu ?', 
#     'iPhone SE 2022 có sẵn không ?', 
#     'Sự khác_biệt về giá giữa iPhone 12 và 13 là gì ?', 
#     'Motorola Edge 20 có sẵn không ?', 
#     'Google Pixel 6 Pro có sẵn ở cửa_hàng của bạn không ?', 
#     'Bạn có bán Xiaomi Mi 11 không ?', 
#     'Có chương_trình ưu_đãi nào cho Samsung Galaxy_Z Fold 3 không ?', 
#     'Oppo Find X3_Pro có sẵn không ?', 
#     'Các tính_năng của iPhone 13 Pro là gì ?', 
#     'LG Wing có sẵn không ?', 
#     'Nokia 8.3 5G có sẵn không ?', 
#     'Asus ROG Phone 5 có sẵn không ?', 
#     'Bạn có Realme GT không ?', 
#     'Vivo X60_Pro có sẵn không ?', 
#     'Bạn có Honor 50 không ?', 
#     'Tuổi_thọ pin của Samsung Galaxy_A52 là bao_nhiêu ?', 
#     'ZTE Axon 30 có sẵn không ?', 
#     'Bạn có BlackBerry KEY2 không ?', 
#     'Kích_thước màn_hình của iPhone 13 Mini là bao_nhiêu ?',
#       'Bạn có TCL 20 Pro 5G không ?', 
#       'Nokia XR20 có sẵn ở cửa_hàng của bạn không ?',
#         'Giá của Samsung Galaxy_S20 FE là bao_nhiêu ?', 
#         'Bạn có iPhone 12 Pro Max không ?', 
#         'Redmi_Note 10 Pro có sẵn không ?', 
#         'Sự khác_biệt giữa iPhone 12 và iPhone 13 là gì ?', 
#         'Bạn có Sony Xperia 5 II không ?', 
#         'Thời_gian bảo_hành của Samsung Galaxy_S21 là bao_lâu ?',
#           'Google Pixel 5a có sẵn không ?', 
#           'Bạn có OnePlus 8T không ?', 
#           'Giá của iPhone 13 Pro Max là bao_nhiêu ?', 
#           'Samsung Galaxy_Z Flip 3 có sẵn không ?', 
#           'Thông_số kỹ_thuật của Oppo Reno6_Pro là gì ?',
#             'Bạn có Vivo V21 không ?',
#               'Motorola Moto G100 có sẵn không ?', 
#               'Bạn có Huawei Mate 40 Pro không ?', 
#               'Realme 8 Pro có sẵn ở cửa_hàng của bạn không ?', 
#               'Asus Zenfone 8 có sẵn không ?', 
#               'LG Velvet có sẵn không ?', 
#               'Dung_lượng lưu_trữ của iPhone 12 là bao_nhiêu ?', 'Bạn có Honor Magic 3 không ?', 'Xiaomi Mi 11 Ultra có sẵn không ?', 'Bạn có sẵn Samsung Galaxy_S22 không ?', 'Giá của Samsung Galaxy_S22 Ultra là bao_nhiêu ?', 'Samsung Galaxy_Z Fold 4 có màu nào ?', 'Bạn có Samsung Galaxy_A72 không ?', 'Thông_số kỹ_thuật của Samsung Galaxy_S21 Ultra là gì ?', 'Samsung Galaxy_S20 FE có những màu nào ?', 'Bạn có Samsung_Galaxy_Note 21 không ?', 'Samsung Galaxy_A52s có sẵn không ?', 'Có chương_trình khuyến_mãi nào cho Samsung Galaxy_Z Flip 4 không ?', 'Dung_lượng pin của Samsung Galaxy_M32 là bao_nhiêu ?', 'Bạn có bán Samsung Galaxy_A32 không ?', 'Samsung Galaxy_S21 có chống nước không ?', 'Thời_gian bảo_hành của Samsung Galaxy_A52 là bao_lâu ?', 'Samsung Galaxy_A12 có sẵn không ?', 'Bạn có Samsung Galaxy_S20 không ?', 'Samsung Galaxy_Z Fold 3 có_giá bao_nhiêu ?', 'Samsung Galaxy_S22 có camera bao_nhiêu megapixel ?', 'Bạn có bán phụ_kiện cho Samsung Galaxy_A52 không ?', 'Samsung Galaxy_A71 có sẵn không ?', 'Có chương_trình trả_góp cho Samsung Galaxy_S21 không ?', 'Bạn có Samsung Galaxy_A52 5G không ?', 'Samsung Galaxy_A22 có sẵn không ?', 'Giá của Samsung_Galaxy_Note 20 Ultra là bao_nhiêu ?', 'Samsung Galaxy_M51 có sẵn không ?', 'Bạn có Samsung Galaxy_Z Fold 2 không ?', 'Samsung Galaxy_S20 Plus có những màu nào ?', 'Dung_lượng lưu_trữ của Samsung Galaxy_A72 là bao_nhiêu ?', 'Bạn có bán Samsung Galaxy_S10 không ?', 'Samsung Galaxy_A22 5G có sẵn không ?', 'Bạn có Samsung_Galaxy_Note 10 không ?', 'Giá của Samsung Galaxy_A52s là bao_nhiêu ?', 'Samsung Galaxy_A02s có sẵn không ?', 'Bạn có bán Samsung Galaxy_Z Flip không ?', 'Samsung Galaxy_A32 có màu nào ?', 'Samsung Galaxy_S21 FE có sẵn không ?', 'Bạn có Samsung Galaxy_A11 không ?', 'Samsung Galaxy_Z Flip 3 có những màu nào ?', 'Samsung Galaxy_M62 có sẵn không ?', 'Bạn có Samsung Galaxy_A72 5G không ?', 'Samsung_Galaxy_Note 10 Plus có_giá bao_nhiêu ?', 'Bạn có bán Samsung Galaxy_M31 không ?', 'Samsung Galaxy_A52 có camera trước bao_nhiêu megapixel ?', 'Samsung Galaxy_S22 Ultra có sẵn không ?', 'Bạn có Samsung Galaxy_A02 không ?', 'Samsung Galaxy_S21 Ultra có những tính_năng gì nổi_bật ?', 'Bạn có bán Samsung_Galaxy_Note 20 không ?', 'Samsung Galaxy_A52s có_giá bao_nhiêu ?', 'Bạn có Samsung Galaxy_M21 không ?', 'Samsung Galaxy_Z Fold 4 có chống nước không ?', 'Bạn có Samsung Galaxy_A51 không ?', 'Giá của Samsung Galaxy_A32 là bao_nhiêu ?', 'Samsung Galaxy_A72 có camera bao_nhiêu megapixel ?', 'Bạn có Samsung Galaxy_A71 5G không ?', 'Samsung Galaxy_S21 có sẵn không ?', 'Samsung Galaxy_A12 có camera trước bao_nhiêu megapixel ?', 'Bạn có bán Samsung Galaxy_A42 không ?', 'Samsung Galaxy_A52 có chống nước không ?', 'Samsung Galaxy_Z Flip 3 có_giá bao_nhiêu ?', 'Bạn có Samsung Galaxy_M12 không ?', 'Samsung Galaxy_S22 có sẵn không ?', 'Giá của Samsung Galaxy_A52 là bao_nhiêu ?', 'Bạn có Samsung Galaxy_A72 4G không ?', 'Samsung Galaxy_S21 Plus có những tính_năng gì nổi_bật ?', 'Bạn có bán Samsung Galaxy_A02 không ?', 'Samsung_Galaxy_Note 20 Ultra có những màu nào ?', 'Samsung Galaxy_A32 5G có sẵn không ?', 'Bạn có Samsung Galaxy_M31s không ?', 'Samsung Galaxy_S22 Ultra có camera trước bao_nhiêu megapixel ?', 'Bạn có bán Samsung Galaxy_A21s không ?', 'Samsung Galaxy_A52s có chống nước không ?', 'Bạn có Samsung Galaxy_A31 không ?', 'Giá của Samsung Galaxy_S22 là bao_nhiêu ?', 'Bạn có Samsung_Galaxy_Note 20 không ?', 'Samsung Galaxy_A12 có sẵn không ?', 'Samsung Galaxy_S21 Ultra có bao_nhiêu camera ?', 'Bạn có bán Samsung Galaxy_Z Fold 3 không ?', 'Samsung Galaxy_A32 có sẵn không ?', 'Giá của Samsung Galaxy_A52s 5G là bao_nhiêu ?', 'Bạn có Samsung Galaxy_A72 4G không ?', 'Samsung Galaxy_S21 có những màu nào ?', 'Samsung Galaxy_A21s có sẵn không ?', 'Bạn có bán Samsung Galaxy_M42 không ?', 'Samsung Galaxy_Z Flip 4 có camera bao_nhiêu megapixel ?', 'Samsung Galaxy_S21 FE có sẵn không ?', 'Bạn có Samsung Galaxy_A22 không ?', 'Samsung Galaxy_S22 có chống nước không ?', 'Samsung Galaxy_A52s có sẵn không ?', 'Bạn có bán Samsung Galaxy_M51 không ?', 'Samsung Galaxy_A12 có bao_nhiêu dung_lượng lưu_trữ ?', 'Bạn có Samsung Galaxy_A32 5G không ?', 'Samsung Galaxy_S21 Ultra có sẵn không ?', 'Samsung Galaxy_Z Fold 4 có sẵn không ?', 'Bạn có bán Samsung Galaxy_A71 không ?', 'Giá của Samsung Galaxy_A52 là bao_nhiêu ?', 'Bạn có Samsung Galaxy_M62 không ?', 'Samsung Galaxy_A72 có sẵn không ?', 'Bạn có bán Samsung Galaxy_S20 không ?', 'Samsung Galaxy_A52s có bao_nhiêu dung_lượng lưu_trữ ?', 'Bạn có Samsung Galaxy_Z Flip 3 không ?', 'Samsung Galaxy_S21 có camera sau bao_nhiêu megapixel ?', 'Samsung Galaxy_S21 có những màu nào ?', 'Giá của Samsung Galaxy_Z Fold 4 là bao_nhiêu ?', 'Samsung Galaxy_A72 có sẵn không ?', 'Bạn có Samsung Galaxy_A52s không ?', 'Samsung Galaxy_S22 Ultra có màu đen không ?', 'Đánh_giá của khách_hàng về Samsung Galaxy_S21 như thế_nào ?', 'Giá của Samsung Galaxy_S22 so với S21 là bao_nhiêu ?', 'Bạn có bán ốp lưng cho Samsung Galaxy_A52 không ?', 'Samsung Galaxy_A32 có màu tím không ?', 'Bạn có bán Samsung Galaxy_S21 FE không ?', 'Samsung Galaxy_A12 có sẵn với dung_lượng 128GB không ?', 'Giá của Samsung Galaxy_S21 Ultra là bao_nhiêu ?', 'Cửa_hàng có hỗ_trợ trả_góp không ?', 'Bạn có Samsung Galaxy_Z Flip 4 không ?', 'Samsung Galaxy_A52s có những màu nào ?', 'Đánh_giá của khách_hàng về Samsung Galaxy_Z Fold 3 là gì ?', 'Bạn có bán sạc nhanh cho Samsung Galaxy_S21 không ?', 'Giá của Samsung Galaxy_A32 là bao_nhiêu ?', 'Cửa_hàng có bảo_hành cho sản_phẩm Samsung không ?', 'Samsung Galaxy_S22 Ultra có màu xanh không ?', 'Đánh_giá của Samsung Galaxy_A72 như thế_nào ?', 'Bạn có sẵn Samsung Galaxy_S21 Plus không ?', 'Samsung Galaxy_A52 có chống nước không ?', 'Giá của Samsung Galaxy_A12 là bao_nhiêu ?', 'Bạn có Samsung Galaxy_Z Fold 4 với dung_lượng 512GB không ?', 'Samsung Galaxy_S21 có camera sau bao_nhiêu MP ?', 'Đánh_giá của khách_hàng về Samsung Galaxy_S21 FE là gì ?', 'Bạn có bán tai_nghe không dây cho Samsung_Galaxy không ?', 'Giá của Samsung Galaxy_A71 là bao_nhiêu ?', 'Samsung Galaxy_S22 có sẵn màu trắng không ?', 'Bạn có Samsung Galaxy_A12 không ?', 'Đánh_giá của khách_hàng về Samsung Galaxy_A52s là gì ?', 'Cửa_hàng có hỗ_trợ đổi trả sản_phẩm Samsung không ?', 'Samsung Galaxy_A32 có sẵn màu xanh không ?', 'Giá của Samsung Galaxy_S22 Ultra là bao_nhiêu ?', 
#               'Bạn có Samsung Galaxy_S20 FE không ?', 'Samsung Galaxy_Z Flip 3 có sẵn màu đen không ?', 
#               'Đánh_giá của khách_hàng về Samsung Galaxy_A12 là gì ?', 'Cửa_hàng có khuyến_mãi gì không ?', 'Bạn có Samsung Galaxy_S21 Ultra không ?', 
#               'Samsung Galaxy_A52 có camera trước bao_nhiêu MP ?', 'Giá của Samsung Galaxy_Z Fold 3 là bao_nhiêu ?', 'Bạn có sẵn Samsung Galaxy_A72 không ?',
#                 'Samsung Galaxy_S22 có sẵn màu vàng không ?', 'Đánh_giá của khách_hàng về Samsung Galaxy_S21 Ultra là gì ?', 'Bạn có bán_kính cường_lực cho Samsung_Galaxy không ?',
#                   'Samsung Galaxy_A52s có dung_lượng lưu_trữ bao_nhiêu ?', 'Cửa_hàng có chương_trình trả_góp cho Samsung_Galaxy không ?', 'Bạn có Samsung Galaxy_S20 không ?', 
#                   'Samsung Galaxy_Z Flip 4 có camera trước bao_nhiêu MP ?', 'Đánh_giá của Samsung Galaxy_A32 như thế_nào ?', 'Giá của Samsung Galaxy_A52s là bao_nhiêu ?',
#                     'Samsung Galaxy_S21 có sẵn màu tím không ?', 'Bạn có Samsung Galaxy_A32 không ?', 'Samsung Galaxy_Z Flip 3 có sẵn với dung_lượng 256GB không ?',
#                     'Đánh_giá của khách_hàng về Samsung Galaxy_S20 FE là gì ?', 'Cửa_hàng có hỗ_trợ bảo_hành cho sản_phẩm Samsung không ?', 'Bạn có bán phụ_kiện cho Samsung_Galaxy không ?', 
#                     'Giá của Samsung Galaxy_A12 so với A32 là bao_nhiêu ?', 'Samsung Galaxy_S22 có sẵn màu đỏ không ?', 'Bạn có Samsung Galaxy_A52 không ?', 
#                     'Samsung Galaxy_Z Fold 4 có chống nước không ?', 'Đánh_giá của Samsung Galaxy_A52s như thế_nào ?', 'Giá của Samsung Galaxy_S21 Plus là bao_nhiêu ?', 
#                     'Bạn có Samsung Galaxy_A71 không ?', 'Samsung Galaxy_Z Flip 3 có sẵn màu hồng không ?', 'Cửa_hàng có chương_trình giảm_giá nào không ?',
#                       'Bạn có Samsung Galaxy_A12 với màu đen không ?', 'Samsung Galaxy_S21 Ultra có bao_nhiêu dung_lượng lưu_trữ ?', 'Đánh_giá của khách_hàng về Samsung Galaxy_Z Flip 4 là gì ?',
#                         'Giá của Samsung Galaxy_A32 là bao_nhiêu ?', 'Bạn có Samsung Galaxy_S21 FE không ?', 'Samsung Galaxy_Z Flip 3 có sẵn màu xanh không ?', 
#                         'Đánh_giá của Samsung Galaxy_A71 như thế_nào ?', 'Bạn có bán Samsung Galaxy_A52s không ?', 'Có màu trắng không', 'Có màu đen không', 
#                         'Có màu xanh không', 'Có màu đỏ không', 'Có màu vàng không', 'Có màu hồng không', 'Có màu tím không', 'Có màu xám không', 'Có màu bạc không', 
#                         'Có màu vàng đồng không', 'Có màu cam không', 'Có màu nâu không', 'Có màu xanh_lam không', 'Có màu xanh lá không', 'Có màu xanh dương không', 
#                         'Có màu xanh lục không', 'Có màu xanh ngọc không', 'Có màu xanh biển không', 'Có màu xanh da_trời không', 'Có màu xanh coban không', 
#                         'Có màu xanh đen không', 'Có màu xanh da_trời không', 'Có màu xanh coban không', 'Có màu xanh đen không',
#                         ]
lawSample = [
    "Thủ tục ly hôn cần những giấy tờ gì?",
    "Ly hôn đơn phương và ly hôn thuận tình khác nhau như thế nào?",
    "Cách chia tài sản khi ly hôn như thế nào?",
    "Con cái sẽ ở với ai sau khi ly hôn?",
    "Có cần phải ra tòa để giải quyết ly hôn không?",
    "Điều kiện để được ly hôn là gì?",
    "Tôi có thể yêu cầu chồng/vợ chu cấp sau khi ly hôn không?",
    "Ly hôn có mất nhiều thời gian không?",
    "Ai sẽ chịu trách nhiệm trả nợ chung sau khi ly hôn?",
    "Tôi có thể giành quyền nuôi con khi ly hôn không?",
    "Chồng/vợ tôi ngoại tình, tôi có thể ly hôn không?",
    "Tôi có thể yêu cầu bồi thường khi chồng/vợ ngoại tình không?",
    "Có bắt buộc phải chia tài sản khi ly hôn không?",
    "Tài sản riêng trước hôn nhân có bị chia khi ly hôn không?",
    "Thủ tục đăng ký kết hôn như thế nào?",
    "Hôn nhân giữa người Việt Nam và người nước ngoài cần những thủ tục gì?",
    "Tôi muốn thay đổi họ của con sau khi ly hôn, cần làm thế nào?",
    "Làm sao để chứng minh tài sản riêng khi ly hôn?",
    "Khi nào thì cần phải lập di chúc?",
    "Cách phân chia tài sản thừa kế như thế nào?",
    "Quy định về việc cấp dưỡng con cái sau khi ly hôn ra sao?",
    "Ly hôn khi chồng/vợ ở nước ngoài thì phải làm thế nào?",
    "Có thể ly hôn khi chồng/vợ đang ở tù không?",
    "Chồng/vợ tôi bạo hành, tôi có thể yêu cầu ly hôn ngay không?",
    "Cách thức yêu cầu chia tài sản chung khi ly hôn?",
    "Chồng/vợ không chịu ký đơn ly hôn thì phải làm sao?",
    "Tôi có quyền giữ tài sản chung sau khi ly hôn không?",
    "Tôi có thể thay đổi quyền nuôi con sau khi đã ly hôn không?",
    "Phân chia tài sản chung theo luật như thế nào?",
    "Thủ tục nhận con nuôi như thế nào?",
    "Có cần thỏa thuận trước hôn nhân về tài sản không?",
    "Ly hôn có cần phải thông qua hòa giải không?",
    "Khi nào thì cần sự tham gia của luật sư trong vụ ly hôn?",
    "Chồng/vợ từ chối cấp dưỡng con cái thì phải làm sao?",
    "Tôi có thể yêu cầu tòa án định giá tài sản chung không?",
    "Có thể yêu cầu tòa án thay đổi quyết định nuôi con không?",
    "Tôi có thể yêu cầu ly hôn khi đang mang thai không?",
    "Có cần giấy xác nhận tình trạng hôn nhân khi kết hôn không?",
    "Khi nào thì tài sản riêng bị coi là tài sản chung?",
    "Quyền và nghĩa vụ của cha mẹ đối với con cái sau khi ly hôn?",
    "Tôi cần làm gì nếu chồng/vợ không đồng ý ly hôn?",
    "Kết hôn với người nước ngoài có cần điều kiện đặc biệt gì không?",
    "Có thể yêu cầu hủy hôn nhân nếu phát hiện chồng/vợ có tiền án không?",
    "Tôi có thể giữ tài sản riêng trong hôn nhân như thế nào?",
    "Nếu một bên ngoại tình, bên kia có được quyền nuôi con không?",
    "Tôi cần làm gì nếu chồng/vợ yêu cầu ly hôn đơn phương?",
    "Có thể giữ bí mật ly hôn với người khác không?",
    "Quyền lợi của con ngoài giá thú như thế nào khi ly hôn?",
    "Có cần bằng chứng cụ thể để yêu cầu ly hôn không?",
    "Tôi có thể yêu cầu ly hôn nếu chồng/vợ không chịu trách nhiệm với gia đình không?",
    "Khi nào thì cần phải lập di chúc?",
    "Cách phân chia tài sản thừa kế như thế nào?",
    "Quy định về việc cấp dưỡng con cái sau khi ly hôn ra sao?",
    "Ly hôn khi chồng/vợ ở nước ngoài thì phải làm thế nào?",
]
chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Làm thế nào để nấu món phở bò ngon?",
    "Tôi có thể tìm sách miễn phí ở đâu?",
    "Bạn có thể giới thiệu một bộ phim hay không?",
    "Làm sao để tôi cải thiện kỹ năng nói tiếng Anh?",
    "Công dụng của mật ong là gì?",
    "Tôi có thể trồng cây gì trong mùa hè?",
    "Cách làm bánh mì tại nhà như thế nào?",
    "Thành phố nào đẹp nhất để du lịch tại Việt Nam?",
    "Tôi nên mua điện thoại hãng nào?",
    "Bài hát nào đang thịnh hành hiện nay?",
    "Làm sao để tập yoga hiệu quả?",
    "Cách chăm sóc da mùa đông là gì?",
    "Tôi nên đọc sách gì để phát triển bản thân?",
    "Bạn có biết cách làm món sushi không?",
    "Làm thế nào để có giấc ngủ ngon?",
    "Tôi nên tập thể dục bao nhiêu lần mỗi tuần?",
    "Có thể giới thiệu một nhà hàng ngon ở Hà Nội không?",
    "Làm thế nào để tiết kiệm tiền hiệu quả?",
    "Tôi nên học lập trình ngôn ngữ nào đầu tiên?",
    "Cách sửa xe đạp tại nhà như thế nào?",
    "Làm sao để quản lý thời gian tốt hơn?",
    "Bạn có thể giới thiệu một cuốn sách hay không?",
    "Tôi có thể tìm hiểu về lịch sử thế giới ở đâu?",
    "Làm thế nào để xây dựng một blog cá nhân?",
    "Bạn có thể giải thích nguyên lý của động cơ đốt trong không?",
    "Cách trồng rau trong nhà kính như thế nào?",
    "Tôi nên học tiếng Anh trực tuyến ở đâu?",
    "Bạn có thể chỉ tôi cách làm nước ép trái cây không?",
    "Làm sao để thiết kế một trang web đẹp?",
    "Tôi có thể giảm cân một cách lành mạnh như thế nào?",
    "Làm thế nào để bắt đầu kinh doanh online?",
    "Tôi có thể học vẽ từ đâu?",
    "Bạn có thể hướng dẫn cách làm video trên YouTube không?",
    "Cách tốt nhất để học lập trình là gì?",
    "Tôi có thể tìm nguồn cảm hứng ở đâu?",
    "Làm thế nào để cải thiện kỹ năng giao tiếp?",
    "Tôi nên chọn trường đại học nào để học ngành IT?",
    "Cách trồng hoa hồng trong chậu như thế nào?",
    "Bạn có thể giải thích về blockchain không?",
    "Làm sao để quản lý chi tiêu hiệu quả?",
    "Tôi nên bắt đầu học chơi guitar như thế nào?",
    "Cách tạo một kế hoạch kinh doanh là gì?",
    "Bạn có thể giới thiệu vài phim khoa học viễn tưởng hay không?",
    "Tôi có thể tìm tài liệu học ngoại ngữ miễn phí ở đâu?",
    "Làm thế nào để quản lý căng thẳng trong công việc?",
    "Cách học tiếng Nhật nhanh chóng là gì?",
    "Tôi có thể tập thể hình tại nhà như thế nào?",
    "Bạn có thể giải thích về trí tuệ nhân tạo không?",
    "Hôm nay là ngày bao nhiêu",
    "Thời gian hiện tại là bao nhiêu",
    "Ngày mai là ngày gì",
    "Ngày hôm nay là thứ mấy",
    "Thời tiết hôm nay như thế nào",
]

# chitchatSample = [
#     'Thời_tiết hôm_nay như thế_nào ?',
#     'Ngoài_trời nóng bao_nhiêu ?', 
#     'Ngày_mai có mưa không ?', 'Nhiệt_độ hiện_tại là bao_nhiêu ?', 
#     'Bạn có_thể cho tôi biết điều_kiện thời_tiết hiện_tại không ?', 
#     'Cuối tuần này có nắng không ?', 'Nhiệt_độ hôm_qua là bao_nhiêu ?', 'Đêm nay trời sẽ lạnh đến mức nào ?', 
#     'Ai là tổng_thống đầu_tiên của Hoa_Kỳ ?', 'Chiến_tranh thế_giới thứ hai kết_thúc vào năm nào ?', 'Bạn có_thể kể cho tôi về lịch_sử của internet không ?', 'Tháp_Eiffel được xây_dựng vào năm nào ?', 'Ai đã phát_minh ra điện_thoại ?', 'Tên của bạn là gì ?', 'Bạn có tên không ?', 'Tôi nên gọi bạn là gì ?', 'Ai đã tạo ra bạn ?', 'Bạn bao_nhiêu tuổi ?', 'Bạn có_thể kể cho tôi một sự_thật thú_vị không ?', 'Bạn có biết bất_kỳ câu_đố thú_vị nào không ?', 'Màu_sắc yêu thích của bạn là gì ?', 'Bộ phim yêu thích của bạn là gì ?', 'Bạn có sở_thích nào không ?', 'Ý_nghĩa của cuộc_sống là gì ?', 'Bạn có_thể kể cho tôi một câu_chuyện cười không ?', 'Thủ_đô của Pháp là gì ?', 'Dân_số thế_giới là bao_nhiêu ?', 'Có bao_nhiêu châu_lục ?', "Ai đã viết ' Giết con chim nhại ' ?", 'Bạn có_thể cho tôi một câu nói của Albert Einstein không ?', 'Vũ_trụ có bao_nhiêu ngôi_sao ?', 'Sao_Hỏa có bao_nhiêu mặt_trăng ?', 'Con_người có_thể sống trên sao Kim không ?', 'Khoảng_cách từ Trái_Đất đến Mặt_Trời là bao_nhiêu ?', 'Loài_vật nào chạy nhanh nhất trên cạn ?', 'Bạn thích loài động_vật nào nhất ?', 'Tại_sao bầu_trời có màu xanh ?', 'Bạn có_thể giúp tôi tính diện_tích của hình tam_giác không ?', "Ai đã vẽ bức tranh ' Mona Lisa ' ?", 'Sông nào dài nhất trên thế_giới ?', 'Bạn có_thể nói cho tôi biết sự khác_biệt giữa đạo Phật và đạo Thiên_Chúa không ?', 'Quốc_gia nào có dân_số đông nhất ?', 'Bạn có_thể kể tên ba thành_phố lớn nhất trên thế_giới không ?', 'Ai là người đầu_tiên bay vào vũ_trụ ?', 'Nước nào là quê_hương của pizza ?', "Thành_phố nào được mệnh_danh là ' Thành_phố ánh_sáng ' ?", 'Bạn có biết bất_kỳ câu thành_ngữ tiếng Việt nào không ?', 'Cuốn sách nào đã bán_chạy nhất mọi thời_đại ?', 'Ngày Tết cổ_truyền của Việt_Nam là ngày nào ?', 'Tháng nào trong năm có ngày ngắn nhất ?', 'Ai là nhà khoa_học nổi_tiếng với thuyết tiến_hóa ?', 'Thức uống nào phổ_biến nhất trên thế_giới sau nước ?', 'Ngôn_ngữ nào được sử_dụng nhiều nhất trên internet ?', 'Bạn có_thể cho tôi biết một bí_mật không ?', 'Con đường nào dài nhất thế_giới ?', 'Châu_Phi có bao_nhiêu quốc_gia ?', 'Màu cờ của Nhật_Bản là gì ?', 'Tên của nữ hoàng Anh hiện_tại là gì ?', 'Núi nào cao nhất trên thế_giới ?', 'Vịnh Hạ_Long thuộc tỉnh nào của Việt_Nam ?', 'Bạn có biết hát không ?', 'Bạn có biết múa không ?', 'Con_số nào lớn nhất trong toán_học ?', 'Ai là người đã tạo ra Mickey_Mouse ?', 'Tên của cây cầu nổi_tiếng ở San_Francisco là gì ?', 'Quốc_gia nào có hình_dạng giống một chiếc ủng ?', 'Người đứng đầu Vatican được gọi là gì ?', 'Bạn có_thể giải_thích luật hấp_dẫn không ?', 'Làm thế_nào để trồng cây từ hạt_giống ?', 'Con sông nào dài nhất Việt_Nam ?', 'Biển nào sâu nhất thế_giới ?', 'Bạn có_thể cho tôi biết cách nấu món phở không ?', 'Tên của bộ phim đoạt giải Oscar nhiều nhất là gì ?', 'Bạn có biết bài hát nào đang thịnh_hành không ?', 'Tên của vị thần sấm_sét trong thần_thoại Hy Lạp là gì ?', 'Loại trái_cây nào có nhiều vitamin C nhất ?', 'Số_nguyên_tố là gì ?', 'Bạn có_thể dịch câu này sang tiếng Anh không ?', 'Quyển sách yêu thích của bạn là gì ?', 'Ngày nào là ngày Quốc_tế Phụ_nữ ?', 'Ai đã phát_minh ra bóng đèn ?', 'Làm thế_nào để làm bánh_mì ?', 'Mặt_trăng có khí_quyển không ?', 'Cây nào cao nhất thế_giới ?', 'Làm thế_nào để trồng hoa_hồng ?', 'Tên của lễ_hội lớn nhất ở Nhật_Bản là gì ?', 'Bạn có biết bài thơ nào hay không ?', 'Tại_sao nước biển lại mặn ?', 'Động_vật nào sống lâu nhất ?', 'Bạn có_thể chỉ tôi cách thắt cà_vạt không ?', "Ai đã viết tác_phẩm ' Hamlet ' ?", 'Con vật nào được coi là biểu_tượng của sự thông_minh ?', "Bạn có_thể giải_thích khái_niệm ' hố_đen ' trong vũ_trụ không ?", 'Cây gì có_thể sống lâu nhất ?', 'Người Việt_Nam đầu_tiên bay vào vũ_trụ là ai ?', 'Bạn có_thể cho tôi biết câu_chuyện về con rùa và con thỏ không ?', 'Bạn có thích chơi trò_chơi không ?', 'Mặt_trời sẽ tồn_tại bao_lâu nữa ?', 'Tại_sao chúng_ta lại cần ngủ ?', 'Bạn có_thể dạy tôi cách làm toán không ?', 'Loài hoa nào được coi là biểu_tượng của tình_yêu ?', 'Ai là người đầu_tiên lên Mặt_Trăng ?', 'Bạn có_thể cho tôi biết công_thức của nước không ?', 'Tên của hoàng đế đầu_tiên của Trung_Quốc là gì ?', 'Bạn có_thể kể cho tôi một câu_chuyện dân_gian không ?', 'Làm thế_nào để nuôi_dưỡng một cây bonsai ?', 'Loài chim nào có_thể bay lùi ?', 'Bạn có_thể giúp tôi làm bài_tập về nhà không ?', "Ai là tác_giả của ' Harry_Potter ' ?", 'Đại_dương nào lớn nhất thế_giới ?', 'Thức uống nào phổ_biến nhất ở Việt_Nam ?', 'Tại_sao lại có bốn mùa trong năm ?', "Tên của con vật nổi_tiếng trong bộ phim ' Finding Nemo ' là gì ?", "Bạn có_thể giải_thích khái_niệm ' năng_lượng mặt_trời ' không ?", 'Ai là người phát_minh ra máy_tính ?', 'Cách tốt nhất để học một ngôn_ngữ mới là gì ?', 'Bạn có_thể nói cho tôi biết về đất_nước của bạn không ?', 'Tên của thành_phố lớn nhất ở Canada là gì ?', 'Bạn có thích du_lịch không ?', 'Tên của con sông dài nhất châu Âu_là gì ?', 'Múi_giờ của Việt_Nam là gì ?', 
#     'Ai là người lãnh_đạo cuộc Cách_mạng Tháng Mười Nga ?', 'Làm thế_nào để làm kem tại nhà ?', 'Bạn có_thể kể tên ba ngọn núi cao nhất thế_giới không ?', 'Ai là người đã sáng_lập ra Facebook ?', 'Bạn có_thể giải_thích sự khác_biệt giữa tiểu_thuyết và truyện_ngắn không ?', 'Tên của hòn đảo lớn nhất thế_giới là gì ?', 'Bạn có_thể nói cho tôi biết về lịch_sử của cây cầu Golden_Gate không ?', 'Thức_ăn truyền_thống của Việt_Nam là gì ?', 'Tại_sao lá cây lại có màu xanh ?', 'Loài cá nào lớn nhất thế_giới ?', 'Bạn có_thể kể cho tôi một câu_chuyện cổ_tích không ?', 'Tên của vị vua nổi_tiếng trong lịch_sử Anh là gì ?', "Bạn có_thể giải_thích khái_niệm ' công_bằng xã_hội ' không ?", 'Ai là nhà triết_học nổi_tiếng của Hy Lạp cổ_đại ?', "Thành_phố nào được gọi là ' Thành_phố của những giấc mơ ' ?", 'Bạn có_thể kể tên ba quốc_gia sử_dụng đồng_tiền Euro không ?', 'Làm thế_nào để nuôi một con cá_cảnh ?', 'Bạn có biết câu tục_ngữ nào hay không ?', "Ai đã viết tác_phẩm ' Cuốn theo chiều gió ' ?", 'Bạn có_thể kể cho tôi về sự phát_triển của thành_phố New_York không ?', 'Tại_sao chúng_ta cần ăn_uống ?', 'Bạn có_thể cho tôi biết cách giảm stress không ?', 'Tên của loài cây nào có_thể sống mà không cần nhiều nước ?', 'Ai là người đầu_tiên phát_minh ra máy_bay ?', 'Bạn có biết làm thế_nào để trồng rau tại nhà không ?', 'Loài_vật nào có_thể sống dưới nước mà không cần thở ?', 'Bạn có_thể kể cho tôi một câu_chuyện hài không ?', 'Tại_sao bầu_trời có màu xanh_lam ?', "Bạn có_thể giải_thích khái_niệm ' tự_do ' không ?", "Ai là tác_giả của ' Đắc nhân_tâm ' ?", 'Bạn có biết cách làm thế_nào để trồng hoa_lan không ?', 'Loài động_vật nào có_thể sống lâu nhất mà không cần ăn ?', 'Tên của bức tranh nổi_tiếng của Leonardo da Vinci là gì ?', "Bạn có_thể giải_thích khái_niệm ' động_cơ đốt trong ' không ?", 'Làm thế_nào để chăm_sóc một con mèo ?', 'Ai là người lãnh_đạo cuộc cách_mạng công_nghiệp ?', 'Bạn có_thể kể tên ba loài chim không biết bay không ?', 'Làm thế_nào để trồng cây_xanh trong nhà ?', 'Tên của bộ phim đoạt giải Oscar năm 2020 là gì ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng tái_tạo ' không ?", 'Ai là người phát_minh ra xe_đạp ?', "Bạn có_thể nói cho tôi biết về tác_phẩm ' Chiến_tranh và hòa bình ' không ?", 'Tại_sao núi_lửa lại phun trào ?', 'Bạn có_thể kể tên ba loại_hình nghệ_thuật không ?', 'Ai là người sáng_lập ra Microsoft ?', "Bạn có_thể giải_thích khái_niệm ' hệ điều_hành ' không ?", 'Làm thế_nào để tiết_kiệm năng_lượng trong gia_đình ?', 'Tên của bức tranh nổi_tiếng của Vincent van Gogh là gì ?', 'Bạn có_thể kể cho tôi về một truyền_thuyết Việt_Nam không ?', 'Tại_sao chúng_ta lại cần học toán ?', 'Tên của đại_dương bao quanh Nam_Cực là gì ?', "Bạn có_thể giải_thích khái_niệm ' blockchain ' không ?", "Ai là tác_giả của ' Người_tình Sputnik ' ?", 'Bạn có_thể cho tôi biết cách làm món bánh_trôi không ?', 'Loài động_vật nào sống ở Bắc_Cực mà không ở Nam_Cực ?', 'Bạn có_thể kể cho tôi về một câu_chuyện ngụ_ngôn không ?', 'Ai là người đã sáng_tạo ra lý_thuyết tương_đối ?', "Bạn có_thể giải_thích khái_niệm ' trí_tuệ nhân_tạo ' không ?", 'Tên của con sông chảy qua thành_phố London là gì ?', 'Bạn có biết cách nào để học nhanh hơn không ?', "Ai là tác_giả của bài hát ' Imagine ' ?", 'Bạn có_thể kể tên ba nhạc_sĩ nổi_tiếng không ?', 'Tên của thủ_đô nước Ý là gì ?', "Bạn có_thể giải_thích khái_niệm ' kinh_tế_học ' không ?", 'Làm thế_nào để nuôi một con chó cưng ?', 'Ai là người phát_minh ra điện_thoại thông_minh ?', 'Bạn có_thể kể tên ba tôn_giáo lớn nhất thế_giới không ?', 'Tên của bức tượng nổi_tiếng ở New_York là gì ?', "Bạn có_thể giải_thích khái_niệm ' quang_hợp ' không ?", 'Ai là người đã tạo ra Facebook ?', 'Làm thế_nào để giảm_thiểu ô_nhiễm môi_trường ?', 'Bạn có_thể kể tên ba loại_hình âm_nhạc không ?', "Ai là tác_giả của ' Thần khúc ' ?", "Bạn có_thể giải_thích khái_niệm ' đạo_đức_học ' không ?", 'Làm thế_nào để chăm_sóc một cây_cảnh ?', 'Tên của hòn đảo lớn nhất ở Nhật_Bản là gì ?', 'Bạn có_thể kể cho tôi về sự phát_triển của thành_phố Hà_Nội không ?', 'Tại_sao cá lại sống dưới nước ?', 'Bạn có_thể cho tôi biết cách để tăng_cường sức_khỏe không ?', 'Tên của loài vật nào có_thể thay_đổi màu_sắc để ngụy_trang ?', 'Ai là người phát_minh ra tàu_hỏa ?', 'Bạn có_thể kể tên ba quốc_gia có nền kinh_tế lớn nhất thế_giới không ?', 'Tên của loài chim biểu_tượng của nước Mỹ là gì ?', "Bạn có_thể giải_thích khái_niệm ' điện_toán đám mây ' không ?", "Ai là tác_giả của tác_phẩm ' 1984 ' ?", 'Bạn có_thể kể cho tôi một câu_chuyện thần_thoại Hy Lạp không ?', "Tên của con vật nổi_tiếng trong bộ phim ' The_Lion_King ' là gì ?", "Bạn có_thể giải_thích khái_niệm ' năng_lượng gió ' không ?", 'Ai là người sáng_lập ra Tesla ?', "Bạn có_thể nói cho tôi biết về tác_phẩm ' Đồi_gió hú ' không ?", 'Tại_sao lá cây lại chuyển màu vào mùa thu ?', 'Bạn có_thể kể tên ba loại thực_phẩm tốt cho sức_khỏe không ?', 'Tên của con vật nào có khả_năng tái_sinh các phần cơ_thể bị mất ?', "Bạn có_thể giải_thích khái_niệm ' chuỗi thức_ăn ' không ?", 'Ai là người sáng_lập ra nền văn_học hiện_đại ?', 'Bạn có_thể kể cho tôi một câu_chuyện cổ_tích nổi_tiếng không ?', 'Tên của loài vật có_thể bay mà không có cánh là gì ?', "Bạn có_thể giải_thích khái_niệm ' tế_bào ' không ?", 'Ai là người phát_minh ra kính thiên_văn ?', 'Bạn có biết cách nào để cải_thiện trí_nhớ không ?', 'Tên của loài hoa nào chỉ nở vào ban_đêm ?', 'Bạn có_thể kể tên ba phát_minh quan_trọng trong lịch_sử loài_người không ?', 'Tại_sao chúng_ta cần uống nước ?', "Bạn có_thể giải_thích khái_niệm ' dòng_chảy điện ' không ?", 'Ai là người phát_minh ra điện ?', 'Bạn có_thể kể tên ba sự_kiện lịch_sử quan_trọng không ?', 'Tên của loài vật sống lâu nhất là gì ?', "Bạn có_thể giải_thích khái_niệm ' động_lực_học ' không ?", "Ai là tác_giả của tác_phẩm ' Moby Dick ' ?", 'Bạn có_thể kể tên ba cuộc chiến_tranh nổi_tiếng không ?', 'Tên của dãy núi nào dài nhất thế_giới ?', "Bạn có_thể giải_thích khái_niệm ' vật_lý lượng_tử ' không ?", 'Ai là người sáng_lập ra Amazon ?', 'Bạn có_thể kể tên ba tác_phẩm văn_học nổi_tiếng không ?', 'Tên của loài cá nào có khả_năng phát sáng là gì ?', "Bạn có_thể giải_thích khái_niệm ' tư_duy phản_biện ' không ?", "Ai là tác_giả của bài hát ' Yesterday ' ?", 'Bạn có_thể kể tên ba nhạc_cụ cổ_điển không ?', 'Tên của thủ_đô nước Úc là gì ?', "Bạn có_thể giải_thích khái_niệm ' hệ sinh_thái ' không ?", 'Làm thế_nào để nuôi_dưỡng một cây sen đá ?', 'Ai là người phát_minh ra máy_in ?', 'Bạn có_thể kể tên ba loại_hình nghệ_thuật thị_giác không ?', 'Tên của dải ngân_hà mà chúng_ta đang sống là gì ?', "Bạn có_thể giải_thích khái_niệm ' tiến_hóa ' không ?", 'Ai là người sáng_lập ra Google ?', 'Bạn có_thể kể tên ba phát_minh của Nikola Tesla không ?', 'Tên của loài động_vật nào có khả_năng tái_sinh_phần cơ_thể bị mất ?', "Bạn có_thể giải_thích khái_niệm ' cảm_biến ' không ?", 'Ai là người phát_minh ra xe_máy ?', 'Bạn có_thể kể tên ba nguyên_tố_hóa học không ?', "Tên của con vật nổi_tiếng trong bộ phim ' Frozen ' là gì ?", "Bạn có_thể giải_thích khái_niệm ' điện_trở ' không ?", 'Ai là người phát_minh ra_công_nghệ điện_thoại_di_động ?', 'Bạn có_thể kể tên ba quốc_gia có nền kinh_tế phát_triển không ?', 'Tên của loài vật có khả_năng phun mực là gì ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng nhiệt ' không ?", 'Ai là người sáng_lập ra tập_đoàn Sony ?', 'Bạn có_thể kể tên ba loại năng_lượng tái_tạo không ?', "Tên của con vật nổi_tiếng trong bộ phim ' Toy Story ' là gì ?", "Bạn có_thể giải_thích khái_niệm ' lực hấp_dẫn ' không ?", 'Ai là người phát_minh ra_trò_chơi video ?', 'Bạn có_thể kể tên ba thành_phố lớn nhất ở châu Á không ?', 'Tên của loài vật có khả_năng thay_đổi màu_sắc là gì ?', "Bạn có_thể giải_thích khái_niệm ' công_suất điện ' không ?", 'Ai là người sáng_lập ra tập_đoàn Samsung ?', 'Bạn có_thể kể tên ba dòng sông lớn ở châu Phi không ?', 'Tên của loài vật nào có_thể sống dưới nước và trên cạn ?', "Bạn có_thể giải_thích khái_niệm ' áp_suất khí_quyển ' không ?", 'Ai là người sáng_lập ra tập_đoàn Intel ?', 'Bạn có_thể kể tên ba bộ phim hoạt_hình nổi_tiếng không ?', 'Tên của loài động_vật nào có_thể sống trong điều_kiện cực_kỳ khắc_nghiệt ?', "Bạn có_thể giải_thích khái_niệm ' công_suất nhiệt ' không ?", 'Ai là người sáng_lập ra tập_đoàn Apple ?', 'Bạn có_thể kể tên ba hệ điều_hành phổ_biến không ?', "Tên của con vật nổi_tiếng trong bộ phim ' Up ' là gì ?", "Bạn có_thể giải_thích khái_niệm ' hóa học ' không ?", 'Ai là người sáng_lập ra tập_đoàn Google ?', 'Bạn có_thể kể tên ba loại thực_phẩm tốt cho tim_mạch không ?', 'Tên của loài vật nào có_thể tái_sinh_phần cơ_thể bị mất ?', "Bạn có_thể giải_thích khái_niệm ' tốc_độ ánh_sáng ' không ?", 'Ai là người sáng_lập ra tập_đoàn Facebook ?', 'Bạn có_thể kể tên ba loại_hình âm_nhạc hiện_đại không ?', 'Tên của loài vật nào có khả_năng phát sáng trong bóng_tối ?', "Bạn có_thể giải_thích khái_niệm ' lực ma_sát ' không ?", 'Ai là người phát_minh ra động_cơ đốt trong ?', 'Bạn có_thể kể tên ba loại năng_lượng xanh không ?', 'Tên của loài vật nào có khả_năng sống_sót trong môi_trường khắc_nghiệt nhất ?', "Bạn có_thể giải_thích khái_niệm ' tốc_độ âm_thanh ' không ?", 'Ai là người phát_minh ra máy_giặt ?', 'Bạn có_thể kể tên ba tác_phẩm văn_học cổ_điển không ?', 'Tên của loài động_vật nào có_thể sống mà không cần nước trong một thời_gian dài ?', "Bạn có_thể giải_thích khái_niệm ' điện_áp ' không ?", 'Ai là người phát_minh ra động_cơ hơi_nước ?', 'Bạn có_thể kể tên ba nhà khoa_học nổi_tiếng không ?', 'Tên của loài động_vật nào có khả_năng tái_sinh_phần cơ_thể bị mất ?', "Bạn có_thể giải_thích khái_niệm ' tốc_độ dòng_chảy ' không ?", 'Ai là người phát_minh ra điện_thoại không dây ?', 'Bạn có_thể kể tên ba hệ điều_hành máy_tính phổ_biến không ?', 'Tên của loài vật nào có khả_năng sống_sót trong điều_kiện không trọng_lực ?', "Bạn có_thể giải_thích khái_niệm ' lực cản ' không ?", 'Ai là người phát_minh ra động_cơ phản_lực ?', 'Bạn có_thể kể tên ba nền văn_minh cổ_đại không ?', 'Tên của loài vật nào có khả_năng sống dưới nước và trên cạn ?', "Bạn có_thể giải_thích khái_niệm ' áp_suất không_khí ' không ?", 'Ai là người phát_minh ra động_cơ đốt ngoài ?', 'Bạn có_thể kể tên ba loại năng_lượng không tái_tạo không ?', 'Tên của loài vật nào có khả_năng phát sáng trong bóng_tối ?', "Bạn có_thể giải_thích khái_niệm ' động_năng ' không ?", 'Ai là người phát_minh ra máy phát_điện ?', 'Bạn có_thể kể tên ba loại_hình năng_lượng không tái_tạo không ?', 'Tên của loài vật nào có khả_năng sống_sót trong môi_trường nhiệt_độ cực thấp ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng tiềm_năng ' không ?", 'Ai là người phát_minh ra máy_tính điện_tử ?', 'Bạn có_thể kể tên ba nhà toán_học nổi_tiếng không ?', 'Tên của loài động_vật nào có khả_năng sống mà không cần ăn trong một thời_gian dài ?', "Bạn có_thể giải_thích khái_niệm ' tốc_độ trung_bình ' không ?", 'Ai là người phát_minh ra động_cơ đốt trong ?', 'Bạn có_thể kể tên ba loại_hình năng_lượng xanh không ?', 'Tên của loài vật nào có khả_năng phát ra âm_thanh dưới nước ?', "Bạn có_thể giải_thích khái_niệm ' lực hút ' không ?", 'Ai là người phát_minh ra xe_đạp điện ?', 'Bạn có_thể kể tên ba hệ điều_hành điện_thoại phổ_biến không ?', 'Tên của loài động_vật nào có khả_năng sống_sót trong môi_trường nhiệt_độ cực cao ?', "Bạn có_thể giải_thích khái_niệm ' áp_suất thủy_tĩnh ' không ?", 'Ai là người phát_minh ra động_cơ đốt trong ?', 'Bạn có_thể kể tên ba nhà phát_minh nổi_tiếng không ?',
#     'Tên của loài vật nào có khả_năng thay_đổi màu_sắc để ngụy_trang ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng hạt_nhân ' không ?", 'Ai là người phát_minh ra động_cơ phản_lực ?', 'Bạn có_thể kể tên ba loại_hình năng_lượng tái_tạo không ?', 'Tên của loài vật nào có khả_năng sống_sót trong môi_trường không trọng_lực ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng mặt_trời ' không ?", 'Ai là người phát_minh ra động_cơ đốt trong ?', 'Bạn có_thể kể tên ba nhà vật_lý nổi_tiếng không ?', 
#     'Tên của loài động_vật nào có khả_năng sống_sót trong môi_trường nước_mặn ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng sinh_học ' không ?", 'Ai là người phát_minh ra động_cơ hơi_nước ?', 'Bạn có_thể kể tên ba nhà_hóa học nổi_tiếng không ?', 'Tên của loài vật nào có khả_năng sống mà không cần nước trong một thời_gian dài ?', "Bạn có_thể giải_thích khái_niệm ' động_cơ_nhiệt ' không ?", 'Ai là người phát_minh ra máy_tính điện_tử ?', 'Bạn có_thể kể tên ba nền văn_minh cổ_đại không ?', 'Tên của loài động_vật nào có khả_năng phát sáng trong bóng_tối ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng gió ' không ?", 'Ai là người phát_minh ra máy_tính không dây ?', 'Bạn có_thể kể tên ba loại năng_lượng tái_tạo không ?', 'Tên của loài vật nào có khả_năng sống_sót trong môi_trường không_khí hiếm ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng nhiệt_hạch ' không ?", 'Ai là người phát_minh ra động_cơ đốt ngoài ?', 'Bạn có_thể kể tên ba loại năng_lượng không tái_tạo không ?', 'Tên của loài vật nào có khả_năng sống_sót trong môi_trường nhiệt_độ cực cao ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng hạt_nhân ' không ?", 'Ai là người phát_minh ra động_cơ đốt trong ?', 
#     'Bạn có_thể kể tên ba nhà phát_minh nổi_tiếng không ?', 'Tên của loài vật nào có khả_năng sống mà không cần thức_ăn trong một thời_gian dài ?', "Bạn có_thể giải_thích khái_niệm ' động_cơ_nhiệt ' không ?", 'Ai là người phát_minh ra động_cơ hơi_nước ?', 'Bạn có_thể kể tên ba nhà vật_lý nổi_tiếng không ?', 'Tên của loài vật nào có khả_năng sống_sót trong môi_trường không trọng_lực ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng mặt_trời ' không ?", 'Ai là người phát_minh ra máy_tính điện_tử ?', 'Bạn có_thể kể tên ba nhà toán_học nổi_tiếng không ?', 'Tên của loài động_vật nào có khả_năng phát sáng trong bóng_tối ?', "Bạn có_thể giải_thích khái_niệm ' động_cơ_điện ' không ?", 'Ai là người phát_minh ra động_cơ đốt trong ?', 'Bạn có_thể kể tên ba loại năng_lượng xanh không ?', 'Tên của loài vật nào có khả_năng thay_đổi màu_sắc để ngụy_trang ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng gió ' không ?", 'Ai là người phát_minh ra máy_tính không dây ?', 'Bạn có_thể kể tên ba nhà phát_minh nổi_tiếng không ?', 'Tên của loài vật nào có khả_năng sống mà không cần nước trong một thời_gian dài ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng sinh_học ' không ?", 'Ai là người phát_minh ra động_cơ đốt trong ?', 'Bạn có_thể kể tên ba nhà_hóa học nổi_tiếng không ?', 'Tên của loài động_vật nào có khả_năng sống_sót trong môi_trường nhiệt_độ cực thấp ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng tái_tạo ' không ?", 'Ai là người phát_minh ra động_cơ phản_lực ?', 'Bạn có_thể kể tên ba nền văn_minh cổ_đại không ?', 'Tên của loài vật nào có khả_năng sống_sót trong môi_trường nước_mặn ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng nhiệt_hạch ' không ?", 'Ai là người phát_minh ra máy phát_điện ?', 'Bạn có_thể kể tên ba nhà phát_minh nổi_tiếng không ?', 'Tên của loài vật nào có khả_năng sống_sót trong môi_trường không_khí hiếm ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng tiềm_năng ' không ?", 'Ai là người phát_minh ra động_cơ đốt ngoài ?', 'Bạn có_thể kể tên ba loại_hình năng_lượng tái_tạo không ?', 'Tên của loài vật nào có khả_năng sống_sót trong môi_trường nhiệt_độ cực cao ?', "Bạn có_thể giải_thích khái_niệm ' năng_lượng hạt_nhân ' không ?", 'Ai là người phát_minh ra động_cơ đốt trong ?', 'Bạn có_thể kể tên ba nhà toán_học nổi_tiếng không ?', 'Tên của loài vật nào có khả_năng sống_sót trong môi_trường không trọng_lực ?',
    
#     ]